# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import os
import shutil

"""Creating Directories"""

def create_directory(path):
    try:
        os.makedirs(path)
        print(f"Directory '{path}' created successfully.")
    except FileExistsError:
        print(f"Directory '{path}' already exists.")
    except Exception as e:
        print(f"Error creating directory '{path}': {e}")

"""Listing Directories and Files"""

def list_directory(path):
    try:
        with os.scandir(path) as entries:
            for entry in entries:
                print(entry.name)
    except FileNotFoundError:
        print(f"The directory '{path}' does not exist.")
    except Exception as e:
        print(f"Error listing directory '{path}': {e}")

"""Renaming Directories and Files"""

def rename_item(old_path, new_path):
    try:
        os.rename(old_path, new_path)
        print(f"Renamed '{old_path}' to '{new_path}'.")
    except FileNotFoundError:
        print(f"The item '{old_path}' does not exist.")
    except Exception as e:
        print(f"Error renaming '{old_path}' to '{new_path}': {e}")

"""Deleting Directories and Files"""

def delete_item(path):
    try:
        if os.path.isdir(path):
            shutil.rmtree(path)
            print(f"Directory '{path}' deleted successfully.")
        elif os.path.isfile(path):
            os.remove(path)
            print(f"File '{path}' deleted successfully.")
        else:
            print(f"The item '{path}' does not exist.")
    except Exception as e:
        print(f"Error deleting '{path}': {e}")

""" Main Function to Interact with the User"""

def main():
    while True:
        print("\nDirectory Management System")
        print("1. Create Directory")
        print("2. List Directory")
        print("3. Rename Directory/File")
        print("4. Delete Directory/File")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            path = input("Enter the directory path to create: ")
            create_directory(path)
        elif choice == '2':
            path = input("Enter the directory path to list: ")
            list_directory(path)
        elif choice == '3':
            old_path = input("Enter the current path of the directory/file: ")
            new_path = input("Enter the new path for the directory/file: ")
            rename_item(old_path, new_path)
        elif choice == '4':
            path = input("Enter the path of the directory/file to delete: ")
            delete_item(path)
        elif choice == '5':
            print("Exiting the Directory Management System.")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()